srs/apps/authentication/urls.py
from django.urls import path

from srs.apps.authentication.views import SignUpView, LoginView

app_name = "authentication"

urlpatterns = [
    path('sign-up/', SignUpView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
]

srs/apps/home/urls.py
from django.urls import path

from srs.apps.home.views import HomeView

app_name = "students"

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
]

srs/apps/students/urls.py
from django.urls import path

from srs.apps.students.views import StudentCreateView, StudentDetailView, StudentUpdateView

app_name = "students"

urlpatterns = [
    path('register/', StudentCreateView.as_view(), name='register'),
    path('<int:id>/', StudentDetailView.as_view(), name='detail'),
    path('<int:id>/edit/', StudentUpdateView.as_view(), name='edit'),
]

srs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("srs.apps.home.urls", namespace='home')),
    path('auth/', include("srs.apps.authentication.urls", namespace='authentication')),
    path('students/', include("srs.apps.students.urls", namespace='students')),
    path('admin/', admin.site.urls, ),
]

srs/apps/home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home/index.html"

srs/apps/home/templates/home/index.html
{% extends "srs/srs.html" %}
{% load static %}


{% block internal_css %}
    {{ block.super }}
    <link href="{% static "home/css/home.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="main">
        <div class="content">
            <a href="{% url "authentication:register" %}" class="btn">
                ثبت نام
            </a>
            <a href="{% url "authentication:login" %}" class="btn">
                ورود
            </a>
            <p>
                تئوری دهم، سیستمی برای خلق خدمات و محصولات نوین
            </p>
            <a href="https://www.10.center/" target="_blank"><img src="{% static "home/images/10-Logo_100x100.png" %}"></a>
        </div>
    </div>
{% endblock %}